### ISSUE TITLE
uncaught exception: Cannot read property '_sessionID' of undefined

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.web#217]
**Describe the bug**  
Ich hab mein System aktualisiert und hatte auf einmal folgende uncaught exception und Fehler im Log.
Die IP 192.168.178.20 ist mein Rechner von dem ich aus gerade arbeite, auf welchem ich auch die VIS Oberfläche offen hatte.

**To Reproduce**  
Unbekannt welche Aktion zu dem Fehler geführt hat

**Screenshots & Logfiles**  

```
2022-05-20 20:21:57.923 - info: web.0 (4676) <== Disconnect system.user.admin from 192.168.178.20 vis.0
2022-05-20 20:21:58.355 - error: web.0 (4676) uncaught exception: Cannot read property '_sessionID' of undefined
2022-05-20 20:21:58.358 - error: web.0 (4676) TypeError: Cannot read property '_sessionID' of undefined
at SocketIO.__updateSession (/opt/iobroker/node_modules/iobroker.socketio/lib/socketIO.js:136:20)
at /opt/iobroker/node_modules/iobroker.socketio/lib/socketIO.js:239:26
at Array.forEach ()
at SocketIO.publishAll (/opt/iobroker/node_modules/iobroker.socketio/lib/socketIO.js:237:34)
at Socket.publishAll (/opt/iobroker/node_modules/iobroker.socketio/lib/socket.js:39:30)
at Object.stateChange (/opt/iobroker/node_modules/iobroker.web/main.js:187:30)
at Immediate. (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5909:56)
at processImmediate (internal/timers.js:464:21)
2022-05-20 20:21:58.359 - error: web.0 (4676) Cannot read property '_sessionID' of undefined
2022-05-20 20:21:58.573 - warn: web.0 (4676) requireLog is not supported by this adapter! Please set common.logTransporter to true
2022-05-20 20:21:58.575 - info: web.0 (4676) <== Disconnect system.user.admin from 192.168.178.20 vis.0
2022-05-20 20:21:58.579 - info: web.0 (4676) terminated http server on port 8082
2022-05-20 20:21:58.581 - info: web.0 (4676) terminating
2022-05-20 20:21:58.583 - warn: web.0 (4676) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-05-20 20:21:58.910 - error: host.ioBroker Caught by controller[0]: TypeError: Cannot read property '_sessionID' of undefined
2022-05-20 20:21:58.913 - error: host.ioBroker Caught by controller[0]: at SocketIO.__updateSession (/opt/iobroker/node_modules/iobroker.socketio/lib/socketIO.js:136:20)
2022-05-20 20:21:58.914 - error: host.ioBroker Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.socketio/lib/socketIO.js:239:26
2022-05-20 20:21:58.915 - error: host.ioBroker Caught by controller[0]: at Array.forEach ()
2022-05-20 20:21:58.917 - error: host.ioBroker Caught by controller[0]: at SocketIO.publishAll (/opt/iobroker/node_modules/iobroker.socketio/lib/socketIO.js:237:34)
2022-05-20 20:21:58.918 - error: host.ioBroker Caught by controller[0]: at Socket.publishAll (/opt/iobroker/node_modules/iobroker.socketio/lib/socket.js:39:30)
2022-05-20 20:21:58.919 - error: host.ioBroker Caught by controller[0]: at Object.stateChange (/opt/iobroker/node_modules/iobroker.web/main.js:187:30)
2022-05-20 20:21:58.920 - error: host.ioBroker Caught by controller[0]: at Immediate. (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5909:56)
2022-05-20 20:21:58.921 - error: host.ioBroker Caught by controller[0]: at processImmediate (internal/timers.js:464:21)
2022-05-20 20:21:58.923 - error: host.ioBroker instance system.adapter.web.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2022-05-20 20:21:58.924 - info: host.ioBroker Restart adapter system.adapter.web.0 because enabled
2022-05-20 20:21:59.058 - info: admin.0 (344) ==> Connected system.user.admin from ::ffff:192.168.178.20
2022-05-20 20:22:01.921 - info: admin.0 (344) ==> Connected system.user.admin from ::ffff:192.168.178.20
2022-05-20 20:22:05.197 - info: admin.0 (344) <== Disconnect system.user.admin from ::ffff:192.168.178.20 admin
```

**Versions:**  
Admin 5.4.9
socket.io 6.1.1
Web socket 2.0.3
WEB-Server 5.1.0

**Comment by Feuer-sturm** [comment]
Ich weiß leider nicht, was der Trigger für den Fehler  war, so dass ich es gerade nicht reproduzieren / mit den neuen Versionen gegentesten kann.

**Comment by vepman** [comment]
Bei mir auch ständig:

`(20935) requireLog is not supported by this adapter! Please set common.logTransporter to true`
Versionen:
Admin 5.4.9
socket.io 6.1.3
WEB-Server 5.2.0

**Comment by Apollon77** [comment]
Web 5.2?

**Comment by lobomau76** [comment]
bei mir läuft web 5.2.:

`<html>
<body>


web.0 | 2022-05-24 13:56:58.730 | info | ==> Connected system.user.admin from ::ffff:192.168.1.105
-- | -- | -- | --
web.0 | 2022-05-24 13:56:52.425 | info | <== Disconnect system.user.admin from ::ffff:192.168.1.105 vis.0
web.0 | 2022-05-24 13:56:52.424 | warn | requireLog is not supported by this adapter! Please set common.logTransporter to true
web.0 | 2022-05-24 13:55:28.997 | info | ==> Connected system.user.admin from ::ffff:192.168.1.105
web.0 | 2022-05-24 13:55:21.757 | info | <== Disconnect system.user.admin from ::ffff:192.168.1.105 vis.0
web.0 | 2022-05-24 13:55:21.750 | warn | requireLog is not supported by this adapter! Please set common.logTransporter to true
web.0 | 2022-05-24 13:54:11.648 | info | ==> Connected system.user.admin from ::ffff:192.168.1.105
web.0 | 2022-05-24 13:54:00.776 | info | <== Disconnect system.user.admin from ::ffff:192.168.1.105 vis.0
web.0 | 2022-05-24 13:54:00.775 | warn | requireLog is not supported by this adapter! Please set common.logTransporter to true
web.0 | 2022-05-24 13:52:28.348 | info | ==> Connected system.user.admin from ::ffff:192.168.1.105
web.0 | 2022-05-24 13:52:21.795 | info | <== Disconnect system.user.admin from ::ffff:192.168.1.105 vis.0
web.0 | 2022-05-24 13:52:21.794 | warn | requireLog is not supported by this adapter! Please set common.logTransporter to true
web.0 | 2022-05-24 13:46:07.197 | info | <== Disconnect system.user.admin from ::ffff:192.168.1.105 flot
web.0 | 2022-05-24 13:46:07.196 | warn | requireLog is not supported by this adapter! Please set common.logTransporter to true


</body>
</html>`
