### ISSUE TITLE
web.0 nicht erreichbar

### ISSUE THREAD

**Issue by MathiasJZ** [ioBroker/ioBroker.web#26]
Seit dem Update heute morgen auf 2.4.4 ist der Webserver nicht mehr erreichbar.
Ich bekomme folgende Fehlermeldungen:
`TypeError: server.api.checkRequest is not a function
    at server.app.use (/opt/iobroker/node_modules/iobroker.web/main.js:1019:42)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/iobroker.web/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/iobroker/node_modules/iobroker.web/node_modules/express/lib/router/index.js:317:13)
    at /opt/iobroker/node_modules/iobroker.web/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/iobroker/node_modules/iobroker.web/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/iobroker/node_modules/iobroker.web/node_modules/express/lib/router/index.js:275:10)
    at next (/opt/iobroker/node_modules/iobroker.web/node_modules/express/lib/router/route.js:127:14)
    at server.app.get (/opt/iobroker/node_modules/iobroker.web/main.js:757:13)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/iobroker.web/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/iobroker/node_modules/iobroker.web/node_modules/express/lib/router/route.js:137:13)`
Ein Downgrade und Neustart haben nichts gebracht.
Gruß,
Mathias

**Comment by guergen1** [comment]
Jepp, den selben Fehler habe ich auch!

**Comment by MathiasJZ** [comment]
Gut dann bin ich schon mal weiter.
Geh mal in die Einstellungen von Web und entferne alle Häkchen
Danach deinstallierst Du Web, installierst es neu, zum Schluß ein reboot.
Hat bei mir auch geholfen.

Am 11. Oktober 2019 17:06:40 schrieb guergen1 <notifications@github.com>:

**Comment by MathiasJZ** [comment]
> Jepp, ich kann den selben Fehler bestätigen!
> Downgrade, Neustart hat nichts gebracht!

Hast Du auch in allen Einstellungen die häkchen entfernt?

**Comment by guergen1** [comment]
Ich habe es ohne Neuinstallation wieder laufen: "Eingebautes Simple-API" abschalten, dann läuft es!
Wozu ist das Häkchen egtl...? Ich finde nichts, was grade nicht geht!

**Comment by guergen1** [comment]
OK, ohne "Simple-API" geht alles.

**Comment by GermanBluefox** [comment]
Simple api was fixed

**Comment by guergen1** [comment]
Der Fehler ist noch nicht weg!

**Comment by Apollon77** [comment]
Soimple-api bitte updaten !!
