### ISSUE TITLE
unvalid binding in vis crashes web adapter with jjs-controller 5.0.4

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.web#316]
**Describe the bug**  
I just updated my ioBroker Master to js-controller 5.0.4.
When I now start my vis1, the following messages appear in the log

In my VIS I have stored the following binding for an icon `{val:javascript.0.Google_Maps.nach_Hause_x.Staustufe_0>"0"? "mdui-red-glow": " "}`

![grafik](https://github.com/ioBroker/ioBroker.web/assets/25422320/2b98a596-7031-4d09-a517-e99ae59db7a7)

The following is entered in the CSS tab
```
/* -----
   glow
   ----- */
.mdui-red-glow {
  filter: drop-shadow(0px 0px 2px #F44336) drop-shadow(0px 0px 2px #F44336) drop-shadow(0px 0px 4px #F44336);

}
```

After discussion with @foxriver76 he told me that my binding is wrong and needs to be like this:
`{val:javascript.0.Google_Maps.nach_Hause_x.Staustufe_0;parseInt(val) > 0 ? "mdui-red-glow": ""}`

but the wrong binding should not crash the adaper.

**Versions:**  
 - Adapter version: web v5.5.3, admin v6.5.8, vis v1.4.16
 - JS-Controller version: 5.0.4

**Screenshots & Logfiles**  
```
2023-06-16 20:11:38.257 - error: web.0 (7732) uncaught exception: The pattern "javascript.0.Google_Maps.nach_Hause_x.Staustufe_0>"0"? "mdui-red-glow"" is not a valid ID pattern

2023-06-16 20:11:38.260 - error: web.0 (7732) Error: The pattern "javascript.0.Google_Maps.nach_Hause_x.Staustufe_0>"0"? "mdui-red-glow"" is not a valid ID pattern

at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2415:15)

at pattern2RegEx (/opt/iobroker/node_modules/@iobroker/adapter-core/build/controllerTools.js:94:44)

at SocketCommands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:267:13)

at SocketCommands._subscribeStates (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:489:26)

at Object.commands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1356:25)

at Socket. (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1556:43)

at /opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:100

at Array.forEach ()

at Immediate. (/opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:83)

at processImmediate (node:internal/timers:476:21)

2023-06-16 20:11:38.262 - error: web.0 (7732) The pattern "javascript.0.Google_Maps.nach_Hause_x.Staustufe_0>"0"? "mdui-red-glow"" is not a valid ID pattern

2023-06-16 20:11:38.907 - error: host.ioBrokerTestsystem Caught by controller[0]: URIError: URI malformed

2023-06-16 20:11:38.912 - error: host.ioBrokerTestsystem Caught by controller[0]: at decodeURI ()

2023-06-16 20:11:38.914 - error: host.ioBrokerTestsystem Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.web/main.js:1718:31

2023-06-16 20:11:38.916 - error: host.ioBrokerTestsystem Caught by controller[0]: at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)

2023-06-16 20:11:38.917 - error: host.ioBrokerTestsystem Caught by controller[0]: at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:328:13)

2023-06-16 20:11:38.920 - error: host.ioBrokerTestsystem Caught by controller[0]: at /opt/iobroker/node_modules/express/lib/router/index.js:286:9

2023-06-16 20:11:38.921 - error: host.ioBrokerTestsystem Caught by controller[0]: at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:346:12)

2023-06-16 20:11:38.922 - error: host.ioBrokerTestsystem Caught by controller[0]: at next (/opt/iobroker/node_modules/express/lib/router/index.js:280:10)

2023-06-16 20:11:38.924 - error: host.ioBrokerTestsystem Caught by controller[0]: at getSocketIoFile (/opt/iobroker/node_modules/iobroker.web/main.js:1105:9)

2023-06-16 20:11:38.925 - error: host.ioBrokerTestsystem Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.web/main.js:1260:44

2023-06-16 20:11:38.926 - error: host.ioBrokerTestsystem Caught by controller[0]: at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)

2023-06-16 20:11:38.927 - error: host.ioBrokerTestsystem Caught by controller[1]: Error: The pattern "javascript.0.Google_Maps.nach_Hause_x.Staustufe_0>"0"? "mdui-red-glow"" is not a valid ID pattern

2023-06-16 20:11:38.928 - error: host.ioBrokerTestsystem Caught by controller[1]: at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2415:15)

2023-06-16 20:11:38.929 - error: host.ioBrokerTestsystem Caught by controller[1]: at pattern2RegEx (/opt/iobroker/node_modules/@iobroker/adapter-core/build/controllerTools.js:94:44)

2023-06-16 20:11:38.931 - error: host.ioBrokerTestsystem Caught by controller[1]: at SocketCommands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:267:13)

2023-06-16 20:11:38.932 - error: host.ioBrokerTestsystem Caught by controller[1]: at SocketCommands._subscribeStates (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:489:26)

2023-06-16 20:11:38.933 - error: host.ioBrokerTestsystem Caught by controller[1]: at Object.commands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1356:25)

2023-06-16 20:11:38.934 - error: host.ioBrokerTestsystem Caught by controller[1]: at Socket. (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1556:43)

2023-06-16 20:11:38.935 - error: host.ioBrokerTestsystem Caught by controller[1]: at /opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:100

2023-06-16 20:11:38.936 - error: host.ioBrokerTestsystem Caught by controller[1]: at Array.forEach ()

2023-06-16 20:11:38.938 - error: host.ioBrokerTestsystem Caught by controller[1]: at Immediate. (/opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:83)

2023-06-16 20:11:38.939 - error: host.ioBrokerTestsystem Caught by controller[1]: at processImmediate (node:internal/timers:476:21)

2023-06-16 20:11:38.940 - error: host.ioBrokerTestsystem instance system.adapter.web.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

2023-06-16 20:11:38.942 - info: host.ioBrokerTestsystem Restart adapter system.adapter.web.0 because enabled

2023-06-16 20:12:09.206 - info: host.ioBrokerTestsystem instance system.adapter.web.0 started with pid 8152

2023-06-16 20:12:13.598 - info: web.0 (8152) starting. Version 5.5.3 in /opt/iobroker/node_modules/iobroker.web, node: v18.16.0, js-controller: 5.0.4

2023-06-16 20:12:13.886 - warn: web.0 (8152) Information for Developer: Using the direct "Let's encrypt" module import is deprecated and will be removed in the next js-controller version, use @iobroker/webserver instead

2023-06-16 20:12:13.998 - info: web.0 (8152) socket.io server listening on port 8082

2023-06-16 20:12:14.014 - info: web.0 (8152) http server listening on port 8082

2023-06-16 20:12:15.658 - info: web.0 (8152) ==> Connected system.user.admin from 192.168.178.20

2023-06-16 20:12:15.910 - info: web.0 (8152) <== Disconnect system.user.admin from 192.168.178.20

2023-06-16 20:12:16.434 - info: web.0 (8152) ==> Connected system.user.admin from 192.168.178.20

2023-06-16 20:12:17.644 - info: web.0 (8152) ==> Connected system.user.admin from 192.168.178.20

2023-06-16 20:12:17.803 - info: web.0 (8152) <== Disconnect system.user.admin from 192.168.178.20

2023-06-16 20:12:18.466 - info: web.0 (8152) ==> Connected system.user.admin from 192.168.178.20

2023-06-16 20:12:19.700 - warn: web.0 (8152) Alias alias.0.testobjekte.Temperatur.ACTUAL has no target 12

2023-06-16 20:12:20.146 - error: web.0 (8152) uncaught exception: The pattern "javascript.0.Google_Maps.nach_Hause_x.Staustufe_0>"0"? "mdui-red-glow"" is not a valid ID pattern

2023-06-16 20:12:20.148 - error: web.0 (8152) Error: The pattern "javascript.0.Google_Maps.nach_Hause_x.Staustufe_0>"0"? "mdui-red-glow"" is not a valid ID pattern

at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2415:15)

at pattern2RegEx (/opt/iobroker/node_modules/@iobroker/adapter-core/build/controllerTools.js:94:44)

at SocketCommands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:267:13)

at SocketCommands._subscribeStates (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:489:26)

at Object.commands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1356:25)

at Socket. (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1556:43)

at /opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:100

at Array.forEach ()

at Immediate. (/opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:83)

at processImmediate (node:internal/timers:476:21)

2023-06-16 20:12:20.150 - error: web.0 (8152) The pattern "javascript.0.Google_Maps.nach_Hause_x.Staustufe_0>"0"? "mdui-red-glow"" is not a valid ID pattern

2023-06-16 20:12:20.683 - error: host.ioBrokerTestsystem Caught by controller[0]: Error: The pattern "javascript.0.Google_Maps.nach_Hause_x.Staustufe_0>"0"? "mdui-red-glow"" is not a valid ID pattern

2023-06-16 20:12:20.686 - error: host.ioBrokerTestsystem Caught by controller[0]: at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2415:15)

2023-06-16 20:12:20.687 - error: host.ioBrokerTestsystem Caught by controller[0]: at pattern2RegEx (/opt/iobroker/node_modules/@iobroker/adapter-core/build/controllerTools.js:94:44)

2023-06-16 20:12:20.688 - error: host.ioBrokerTestsystem Caught by controller[0]: at SocketCommands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:267:13)

2023-06-16 20:12:20.689 - error: host.ioBrokerTestsystem Caught by controller[0]: at SocketCommands._subscribeStates (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:489:26)

2023-06-16 20:12:20.690 - error: host.ioBrokerTestsystem Caught by controller[0]: at Object.commands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1356:25)

2023-06-16 20:12:20.692 - error: host.ioBrokerTestsystem Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1556:43)

2023-06-16 20:12:20.693 - error: host.ioBrokerTestsystem Caught by controller[0]: at /opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:100

2023-06-16 20:12:20.694 - error: host.ioBrokerTestsystem Caught by controller[0]: at Array.forEach ()

2023-06-16 20:12:20.695 - error: host.ioBrokerTestsystem Caught by controller[0]: at Immediate. (/opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:83)

2023-06-16 20:12:20.696 - error: host.ioBrokerTestsystem Caught by controller[0]: at processImmediate (node:internal/timers:476:21)

2023-06-16 20:12:20.698 - error: host.ioBrokerTestsystem instance system.adapter.web.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

2023-06-16 20:12:20.699 - info: host.ioBrokerTestsystem Restart adapter system.adapter.web.0 because enabled
```

**Comment by Chaot1** [comment]
Bei mir hat ebenfalls ein fehlerhaftes Binding den Crash verursacht:
`<html>
<body>


host.ioBroker
--
  | 2023-06-17 10:22:01.014	error	instance system.adapter.web.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
  | host.ioBroker
  | 2023-06-17 10:22:01.013	error	Caught by controller[1]: at processImmediate (node:internal/timers:476:21)
  | host.ioBroker
  | 2023-06-17 10:22:01.013	error	Caught by controller[1]: at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:83)
  | host.ioBroker
  | 2023-06-17 10:22:01.013	error	Caught by controller[1]: at Array.forEach (<anonymous>)
  | host.ioBroker
  | 2023-06-17 10:22:01.013	error	Caught by controller[1]: at /opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:100
  | host.ioBroker
  | 2023-06-17 10:22:01.013	error	Caught by controller[1]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1556:43)
  | host.ioBroker
  | 2023-06-17 10:22:01.012	error	Caught by controller[1]: at Object.commands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1356:25)
  | host.ioBroker
  | 2023-06-17 10:22:01.012	error	Caught by controller[1]: at SocketCommands._subscribeStates (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:492:22)
  | host.ioBroker
  | 2023-06-17 10:22:01.011	error	Caught by controller[1]: at SocketCommands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:267:13)
  | host.ioBroker
  | 2023-06-17 10:22:01.011	error	Caught by controller[1]: at pattern2RegEx (/opt/iobroker/node_modules/@iobroker/adapter-core/build/controllerTools.js:94:44)
  | host.ioBroker
  | 2023-06-17 10:22:01.011	error	Caught by controller[1]: at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2415:15)
  | host.ioBroker
  | 2023-06-17 10:22:01.011	error	Caught by controller[1]: Error: The pattern "Samstag<br>17.06.2023" is not a valid ID pattern
  | host.ioBroker
  | 2023-06-17 10:22:01.011	error	Caught by controller[0]: at processImmediate (node:internal/timers:476:21)
  | host.ioBroker
  | 2023-06-17 10:22:01.010	error	Caught by controller[0]: at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:83)
  | host.ioBroker
  | 2023-06-17 10:22:01.010	error	Caught by controller[0]: at Array.forEach (<anonymous>)
  | host.ioBroker
  | 2023-06-17 10:22:01.010	error	Caught by controller[0]: at /opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:100
  | host.ioBroker
  | 2023-06-17 10:22:01.010	error	Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1556:43)
  | host.ioBroker
  | 2023-06-17 10:22:01.010	error	Caught by controller[0]: at Object.commands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1356:25)
  | host.ioBroker
  | 2023-06-17 10:22:01.010	error	Caught by controller[0]: at SocketCommands._subscribeStates (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:492:22)
  | host.ioBroker
  | 2023-06-17 10:22:01.009	error	Caught by controller[0]: at SocketCommands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:267:13)
  | host.ioBroker
  | 2023-06-17 10:22:01.009	error	Caught by controller[0]: at pattern2RegEx (/opt/iobroker/node_modules/@iobroker/adapter-core/build/controllerTools.js:94:44)
  | host.ioBroker
  | 2023-06-17 10:22:01.009	error	Caught by controller[0]: at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2415:15)
  | host.ioBroker
  | 2023-06-17 10:22:01.006	error	Caught by controller[0]: Error: The pattern "Samstag<br>17.06.2023" is not a valid ID pattern
  |  
  | web.0
  | 2023-06-17 10:22:00.556	error	The pattern "Samstag<br>17.06.2023" is not a valid ID pattern
  |  
  | web.0
  | 2023-06-17 10:22:00.555	error	Error: The pattern "Samstag<br>17.06.2023" is not a valid ID pattern at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2415:15) at pattern2RegEx (/opt/iobroker/node_modules/@iobroker/adapter-core/build/controllerTools.js:94:44) at SocketCommands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:267:13) at SocketCommands._subscribeStates (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:492:22) at Object.commands.subscribe (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1356:25) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.ws/node_modules/@iobroker/socket-classes/lib/socketCommands.js:1556:43) at /opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:100 at Array.forEach (<anonymous>) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/ws-server/index.js:152:83) at processImmediate (node:internal/timers:476:21)
  |  
  | web.0
  | 2023-06-17 10:22:00.547	error	uncaught exception: The pattern "Samstag<br>17.06.2023" is not a valid ID pattern


</body>
</html>`

Das Binding:
`{javascript.0.variables.dayTime.lc;momentDate(dddd)}<br>{javascript.0.variables.dayTime.lc;momentDate(DD.MM.YYYY)}`

Versions:

Adapter version: web v5.5.3, admin v6.5.8, vis v1.4.16
JS-Controller version: 5.0.4

**Comment by foxriver76** [comment]
will be fixed with https://github.com/ioBroker/ioBroker.socket-classes/pull/17

**Comment by seb2010** [comment]
Question @foxriver76 & @GermanBluefox on this: if this is fixed in socket-classes, how will this then get distributed to iobroker exactly? I do have the latest packages for all adapters but still am getting the following error:
`Invalid pattern on subscribe: The pattern "<div style="position:absolute;top:3px;right:5px;width:100%px;font-size:12px;color:#a0a0a0"> 22.8.2023, 07:19:51<br>17438.24 m³ </div>" is not a valid ID pattern`
within binding.
The pattern is the content of a html-widget.

**Comment by foxriver76** [comment]
socket-classes will catch it, will in general be distributed with new versions of adapters. However, it is still a configuration issue. Most likely your binding is corrupted and uses the div as an id.

**Comment by seb2010** [comment]
Hi @foxriver76. But how to fix it then?
The content of the html-widget looks like this, which is just a normal binding...:
`<div style="position:absolute;top:3px;right:5px;width:100%px;font-size:12px;color:#a0a0a0">
    {x:javascript.0.Gas.Volumenzähler.ts;new Date(x*1).toLocaleString('de-DE')}<br>{javascript.0.Gas.Volumenzähler} m³
</div>`
The web-adapter seems to not set the ID for this object right and somehow uses the content?!

**Comment by foxriver76** [comment]
looks good in the first place, can you show a screenshot and the used widget.

**Comment by seb2010** [comment]
While trying to past the code, github had trouble interpreting it correctly. The seemingly whitespace before the </div> caused some trouble. Maybe the line-breaks or whitespaces introduced by the html-widget auto-formatting also do interfere with the ID validation...

**Comment by seb2010** [comment]
@foxriver76:
![image](https://github.com/ioBroker/ioBroker.web/assets/57917445/ff57e58d-6347-42ab-8fc4-b3270ac9956c)
