### ISSUE TITLE
Error: Cannot read property 'startsWith' of null

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.web#40]
```
web.0 | 2020-02-29 21:18:41.822 | error | at process._tickCallback (internal/process/next_tick.js:61:11)
web.0 | 2020-02-29 21:18:41.822 | error | at /opt/iobroker/node_modules/socket.io/lib/socket.js:528:12
web.0 | 2020-02-29 21:18:41.822 | error | at Socket.emit (events.js:198:13)
web.0 | 2020-02-29 21:18:41.822 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.socketio/lib/socket.js:1122:30)
web.0 | 2020-02-29 21:18:41.822 | error | at Adapter.getForeignState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5666:24)
web.0 | 2020-02-29 21:18:41.822 | error | (5634) TypeError: Cannot read property 'startsWith' of null
web.0 | 2020-02-29 21:18:41.815 | error | (5634) uncaught exception: Cannot read property 'startsWith' of null
```

**Comment by Apollon77** [comment]
Which version of web and socketio?

**Comment by Zefau** [comment]
`v3.0.1`, but it only happened once it seems.

**Comment by Apollon77** [comment]
it was an id of null for a getForeignState ... I move to controller
